In [3]:
import pandas as pd
import numpy as np
import os

In [8]:
vine_df=pd.read_csv("VDF.csv", header=0)
vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,RTIS3L2M1F5SM,5,0,0,N,Y
1,R1ZV7R40OLHKD,5,0,0,N,Y
2,R3BH071QLH8QMC,1,0,1,N,Y
3,R127K9NTSXA2YH,3,0,0,N,Y
4,R32ZWUXDJPW27Q,4,0,0,N,Y
...,...,...,...,...,...,...
1785992,RPC430LWZJ60T,5,1,1,N,N
1785993,R347MZT5FH6HRJ,5,2,2,N,N
1785994,RJ5BETZP0VIUS,1,0,2,N,N
1785995,R85QTDO2KZMGO,1,1,3,N,N
1785996,R2W36RZZZNTYWF,5,1,1,N,N